name: Unit Test Coverage

on:
  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:

env:
  NODE_VERSION: 16.14.0

permissions:
  contents: read

jobs:
  coverage:
    name: Coverage Check
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install Dependencies
        run: npm ci

      - name: Unit Test Coverage
        if: always()
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          test-script: npx jest -c jest.config.js --ci --json --coverage --testLocationInResults --outputFile=report.json
