name: Report mikepenz dummy test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log Level"
        default: debug
        required: true
      testEnv:
        description: "Environment"
        default: qa
        required: true

env:
  NODE_VERSION: 16.14.0

jobs:
  linting:
    name: QA API test
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: ENV=${{ github.event.inputs.testEnv }} LOG_LEVEL=${{ github.event.inputs.logLevel }} npx gulp test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "**/reports/*.xml"
